bookers2-debug-5/config/routes.rb
Rails.application.routes.draw do
	devise_for :users
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :users,only: [:show,:index,:edit,:update] do
   	# フォロー
   	member do
   		get :following, :followers
   	end
   end
   resources :relationships,only: [:create, :destroy]

   resources :books do
   	# いいね
   	resource :favorites,only: [:create,:destroy]
   	# コメント
   	resource :book_comments, only: [:create]
   end
   root 'home#top'
   get 'home/about' => 'home#about'
   get '/search', to: 'search#search'
end

bookers2-debug-5/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  # いいね
  has_many :favorites, dependent: :destroy
  # コメント
  has_many :book_comments, dependent: :destroy
  # フォロー
  has_many :active_relationships,class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower
  def following?(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end
  def follow!(other_user)
    active_relationships.create!(following_id: other_user.id)
  end
  def unfollw!(other_user)
    active_relationships.find_by(followign_id: other_user.id).destroy
  end

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

bookers2-debug-5/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]
  before_action :authenticate_user!, only: [:index, :show, :edit]
  before_action :correct_user, only: [:edit, :update]
  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def show
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  	@user = User.find(params[:id])
  	@books = @user.books
  end

  # フォロー
  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
  # フォロー


  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end
end

bookers2-debug-5/app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
		user == current_user
	end
end

bookers2-debug-5/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
<div>
	<%= hidden_field_tag :following_id, @user.id %>
</div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

bookers2-debug-5/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
	<% if current_user.following?(@user) %>
	<%= render 'unfollow' %>
	<% else %>
	<%= render 'follow' %>
	<% end %>
</div>
<% end %>

bookers2-debug-5/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug-5/app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>
<!-- フォロー -->
		<%= render 'follow_form' if user_signed_in? %>
		<% @user ||= current_user %>
		<div class="stats">
			<div class= "b2" style = "margin:10px">
			<a href="<%= following_user_path(@user) %>">
				<strong id="following" class="stat" style = "text-decoration:none;">
					<%= @user.followings.count %>
				</strong>
				following
			</a>
		    </div>
		    <div class= "b2" style = "margin:10px">
			<a href="<%= followers_user_path(@user) %>">
				<strong id="followers" class="stat">
					<%= @user.followers.count %>
				</strong>
				followers
			</a>
		    </div>
		</div>
		<!-- フォロー -->
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id} b" %>
</div>

bookers2-debug-5/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btu" %>
<% end %>

bookers2-debug-5/app/views/users/edit.html.erb
<div class="row">
	<h2>User info</h2>

	<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

	<% end %>
</div>

bookers2-debug-5/app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td style="width: 100px; height: 50px;">
						<% unless current_user?(user) %>
						<div id="follow_form">
							<% if current_user.following?(@user) %>
							<%= render 'unfollow' %>
							<% else %>
							<%= render 'follow' %>
							<% end %>
						</div>
						<% end %>
					</td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
		</div>
	</div>

bookers2-debug-5/app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>
	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

bookers2-debug-5/app/views/users/show_follow.html.erb
<div class="row">
	<% @user.followings.each do |user| %>
	<table class="table">
		<thead>
			<tr>
				<th>follow</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td> <%= user.name %> </td>
				<td> <%= link_to 'show', user_path(user) %> </td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>

bookers2-debug-5/app/views/users/show_follower.html.erb
<div class="row">
	<% @user.followers.each do |user| %>
	<table class="table">
		<thead>
			<tr>
				<th>follower</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td> <%= user.name %> </td>
				<td> <%= link_to 'show', followers_user_path(user) %></td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>