bookers2-debug-3-answer/config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  resources :users,only: [:show,:edit,:update,:index]
  root 'home#top'
  get 'home/about'

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

bookers2-debug-3-answer/app/models/book.rb
class Book < ApplicationRecord 
	belongs_to :user
	validates :title, presence: true
	validates :body ,presence: true, length: {maximum: 200}
	has_many :favorites
	has_many :book_comments
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

bookers2-debug-3-answer/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

bookers2-debug-3-answer/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2-debug-3-answer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image, destroy: false
  has_many :books
  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :favorites
end 

bookers2-debug-3-answer/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_new = Book.new
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    if @book_comment.save
      flash[:success] = "Comment was successfully created."
      redirect_to book_path(@book)
    else
      @book_comments = BookComment.where(book_id: @book.id)
      render '/books/show'
    end
  end

  def destroy
    @book_comment = BookComment.find(params[:book_id])
    if @book_comment.user != current_user
      redirect_to request.referer
    end
    @book_comment.destroy
    redirect_to request.referer
    
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2-debug-3-answer/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    screen_user(@book)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def screen_user(book)
      if book.user.id != current_user.id
        redirect_to books_path
      end
    end

end

bookers2-debug-3-answer/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request.referer
  end

  private
  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to books_path
    when 1
      redirect_to book_path(@book)
    end
  end
end

bookers2-debug-3-answer/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!-- いいね機能 -->
        <td>
          <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete do %>
              <%#= fa_icon "heart", text: "#{book.favorites.count}", style: "color: red;" %>
              <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book, redirect_id: 0), method: :post do %>
              <%#= fa_icon "heart-o", text: "#{book.favorites.count}", style: "color: red;" %>
              <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
            <% end %>
          <% end %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug-3-answer/app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render '/books/form', book: Book.new %>
  </div>
  

  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
		  <tr>
        <td><%= link_to(@book.user) do %>
          <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= link_to @book.title, @book %></td>
        <td><%= @book.body %></td>
        <!-- いいね機能 -->
        <td>
          <% if @book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(@book, redirect_id: 0), method: :delete do %>
              <span class="glyphicon glyphicon-heart"><%= @book.favorites.count%></span>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(@book, redirect_id: 0), method: :post do %>
              <span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
            <% end %>
          <% end %>
        </td>
        <td>コメント数：<%= @book.book_comments.count %></td>

        <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{@book.id}"%></td>
        <% end %>
      </tr>
    </table>
    <table class="show-tb">
      <% @book_comments.each do |book_comment| %> <!-- コメント一覧 -->
        <tr>
          <td>
            <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
              <%= book_comment.user.name %>
            <% end %>
          </td>
          <td><%= book_comment.comment %></td>
          <% unless current_user != book_comment.user %>
            <td><%= link_to 'Destroy', book_book_comments_path(book_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <div class="comment-form">
      <%= form_for [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, size: "90x5" %>
        <%= f.submit '送信' %>
      <% end %>
    </div>

  </div>
</div>